// File generated by hand from google-services.json.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe46sD4oNYOsT8vNlABxg3q5cI5YxmSpA',
    appId: '1:131054565517:android:4e527a981b0e824ae48ac4',
    messagingSenderId: '131054565517',
    projectId: 'pokedesk-10479',
    storageBucket: 'pokedesk-10479.firebasestorage.app',
  );

  // iOS config — replace with values from your GoogleService-Info.plist if you
  // add an iOS app to the Firebase project. For now, iOS uses the same API key.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe46sD4oNYOsT8vNlABxg3q5cI5YxmSpA',
    appId: '1:131054565517:ios:placeholder',
    messagingSenderId: '131054565517',
    projectId: 'pokedesk-10479',
    storageBucket: 'pokedesk-10479.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'com.example.eventReminder',
  );
}
